---
# On Distro vars files, replace this to sync packages
native_packages: []

# On OS vars files, replace this to sync dependencies
extra_deps: []

# CLI tools/utilities MUST have
# On Linux: native packages
# On Mac: brew/ports tools
common_deps:
  - bat # github.com/sharkdp/bat
  - curl # curl.se/
  - eza # github.com/eza-community/eza
  - fastfetch # github.com/fastfetch-cli/fastfetch
  - fd # github.com/sharkdp/fd
  - fzf # github.com/junegunn/fzf
  - git # git-scm.com/
  - git-delta # dandavison.github.io/delta
  - jq # jqlang.github.io/jq
  - ripgrep # github.com/BurntSushi/ripgrep
  - unzip # infozip.sourceforge.net/UnZip.html
  - zoxide # github.com/ajeetdsouza/zoxide
  - zsh # zsh.org/

