---
- name: Bootstrap Machine
  hosts: localhost, all
  become: true
  gather_facts: true

  pre_tasks:
    - name: "Init: inject 'Linux' variables"
      when: ansible_facts['system'] == "Linux"
      ansible.builtin.include_vars:
        file: "group_vars/linux.yml"
      tags:
        - always

    - name: "Init: inject 'Arch Linux' variables"
      when: ansible_facts['distribution'] == "Archlinux"
      ansible.builtin.include_vars:
        file: "group_vars/aur.yml"
      tags:
        - always

  roles:
    - name: bootstrap_dependencies
      tags:
        - bootstrap
        - deps

    - name: yay_installer
      tags:
        - yay
        - installer
        - arch

    - name: pacman_packages
      tags:
        - pacman
        - apps
        - arch
        - native

    - name: aur_packages
      tags:
        - aur
        - apps
        - arch

    - name: flatpak_packages
      tags:
        - flatpak
        - apps
