---
# roles/pacman_packages/tasks/main.yml
- name: "Install: 'Repo' packages"
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - (packages_pacman_default | length > 0) or (native_packages | length > 0)
  block:
    - name: "Init: 'read' packages"
      ansible.builtin.set_fact:
        packages: "{{ packages_pacman_default + native_packages }}"

    - name: "Sync: 'Native' packages"
      ansible.builtin.pacman:
        name: "{{ packages }}"
        state: present
        update_cache: true
