---
# roles/fancy_shell/tasks/tools/oh_my_posh.yml
- name: "Install: '{{ item.name }}' prompt engine"
  become: true
  become_user: "{{ dotfiles_user }}"
  vars:
    destination_directory: ~/.local/bin
    destination_script: "/tmp/install-{{ item.name | lower | replace(' ', '-') }}.sh"
  block:
    - name: "Init: ensure '{{ item.name }} destination directory' exists"
      ansible.builtin.file:
        path: "{{ destination_directory }}"
        state: directory
        mode: '0755'

    - name: "Download: 'installer' script"
      ansible.builtin.get_url:
        url: "{{ item.site }}/install.sh"
        dest: "{{ destination_script }}"
        mode: '0755'

    - name: "Install: run 'installer'"
      ansible.builtin.command:
        cmd: "{{ destination_script }} -d {{ destination_directory }}"
      register: oh_my_posh_install
      changed_when: "'is already up to date' not in oh_my_posh_install.stdout"

    - name: Clean up temporary installer script
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ destination_script }}"
        state: absent
